services:
  synapse:
    image: docker.io/matrixdotorg/synapse:v1.117.0@sha256:070236812ba367a90094fd86df0e160da5643a06e5259154f157d44c4c7a2f31
    # Since synapse does not retry to connect to the database, restart upon
    # failure
    restart: 'no'
    # See the readme for a full documentation of the environment settings
    # NOTE: You must edit homeserver.yaml to use postgres, it defaults to sqlite
    environment:
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
    volumes:
      # You may either store all the files in a local folder
      - ./files:/data
      # .. or you may split this between different storage points
      # - ./files:/data
      # - /path/to/ssd:/data/uploads
      # - /path/to/large_hdd:/data/media
    # depends_on:
    #   - db
    # In order to expose Synapse, remove one of the following, you might for
    # instance expose the TLS port directly:
    ports:
      - 8008:8008/tcp

  # db:
  #   image: docker.io/postgres:12-alpine
  #   # Change that password, of course!
  #   environment:
  #     - POSTGRES_USER=synapse
  #     - POSTGRES_PASSWORD=changeme
  #     # ensure the database gets created correctly
  #     # https://matrix-org.github.io/synapse/latest/postgres.html#set-up-database
  #     - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
  #   volumes:
  #     # You may store the database tables in a local folder..
  #     - ./schemas:/var/lib/postgresql/data
  #     # .. or store them on some high performance storage for better results
  #     # - /path/to/ssd/storage:/var/lib/postgresql/data

  synapse-admin:
    container_name: synapse-admin
    hostname: synapse-admin
    image: awesometechnologies/synapse-admin:0.10.3@sha256:70a6e988af1b4acc2f3c0dea8c2eebc27a9ecbe638a472540104625326c5e259
    ports:
      - '8080:80'
    restart: 'no'
